# Generated by Django 5.2.8 on 2025-12-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
